/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-04 11:20:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blog04_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668046164505L));
    _jspx_dependants.put("jar:file:/D:/springbootFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Feidear/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	");
String pjName = "/Feidear";
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title> Feidear 축제 일기 </title>\r\n");
      out.write("    <!-- favicon -->\r\n");
      out.write("    <link rel=icon href=\"images/favicon.png\" sizes=\"20x20\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional plugin css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/slick.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/swiper.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n");
      out.write("    <!-- icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/line-awesome.min.css\">\r\n");
      out.write("    <!-- main css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <!-- responsive css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- preloader area start -->\r\n");
      out.write("    <div class=\"preloader\" id=\"preloader\">\r\n");
      out.write("        <div class=\"preloader-inner\">\r\n");
      out.write("            <div class=\"spinner\">\r\n");
      out.write("                <div class=\"dot1\"></div>\r\n");
      out.write("                <div class=\"dot2\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- preloader area end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- //. sign up Popup -->\r\n");
      out.write("    <div class=\"signUp-popup login-register-popup\" id=\"signUp-popup\">\r\n");
      out.write("        <div class=\"login-register-popup-wrap\">\r\n");
      out.write("            <div class=\"row no-gutters\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"thumb\">\r\n");
      out.write("                        <img src=\"images/others/signup.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                    <div class=\"shape-thumb\">\r\n");
      out.write("                        <img src=\"images/others/signup-shape.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form class=\"login-form-wrap\">\r\n");
      out.write("                        <h4 class=\"text-center\">Sign Up</h4>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Name\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-user\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-envelope\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Password\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-lock\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label class=\"checkbox\">\r\n");
      out.write("                            <input type=\"checkbox\">\r\n");
      out.write("                            <span>Remember me</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <button class=\"btn btn-yellow w-100\">Sign Up</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sign-in-btn\">I already have an account. <a href=\"#\">Sign In</a></div> \r\n");
      out.write("                        <div class=\"social-wrap\">\r\n");
      out.write("                            <p>Or Continue With</p>\r\n");
      out.write("                            <ul class=\"social-icon\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"facebook\" href=\"#\" target=\"_blank\"><i class=\"fa fa-facebook  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"twitter\" href=\"#\" target=\"_blank\"><i class=\"fa fa-twitter  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"pinterest\" href=\"#\" target=\"_blank\"><i class=\"fa fa-pinterest\"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //. sign up Popup End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- navbar area start -->\r\n");
      out.write("    <nav class=\"navbar navbar-area navbar-expand-lg nav-style-01\">\r\n");
      out.write("        <div class=\"container nav-container\">\r\n");
      out.write("            <div class=\"responsive-mobile-menu\">\r\n");
      out.write("                <div class=\"mobile-logo\">\r\n");
      out.write("                    <a href=\"index\">\r\n");
      out.write("                        <img src=\"images/sticky-logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"navbar-toggler float-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#tp_main_menu\" \r\n");
      out.write("                    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggle-icon\">\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"nav-right-content\">\r\n");
      out.write("                    <ul class=\"pl-0\">\r\n");
      out.write("                        <li class=\"top-bar-btn-booking\">\r\n");
      out.write("                            <a class=\"btn btn-yellow\" href=\"tour-details\">Book Now <i class=\"fa fa-paper-plane\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"notification\">\r\n");
      out.write("                            <a class=\"signUp-btn\" href=\"#\">\r\n");
      out.write("                                <i class=\"fa fa-user-o\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"tp_main_menu\">\r\n");
      out.write("                <div class=\"logo-wrapper desktop-logo\">\r\n");
      out.write("                    <a href=\"index\" class=\"main-logo\">\r\n");
      out.write("                        <img src=\"images/logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"index\" class=\"sticky-logo\">\r\n");
      out.write("                        <img src=\"images/sticky-logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"navbar-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"tour-list\">축제</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a href=\"#\">커뮤니티</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                        <!-- 한솔 수정 -->\r\n");
      out.write("                            <li><a href=\"blog04\">축제일기</a></li>			\r\n");
      out.write("                            <li><a href=\"blog-details02\">축제일기 상세</a></li>\r\n");
      out.write("                            <li><a href=\"blog02\">매거진</a></li>\r\n");
      out.write("                            <li><a href=\"blog-details\">매거진 상세</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a href=\"#\">이벤트</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"blog03\">제휴 이벤트</a></li>\r\n");
      out.write("                      		<li><a href=\"destination-details\">서포터즈</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a href=\"#\">스마트 PAGE</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"user-profile\">MY 여행성향 분석</a></li>\r\n");
      out.write("                      		<li><a href=\"user-profile\">실시간 날씨</a></li>\r\n");
      out.write("                      		<li><a href=\"user-profile\">혼잡도 체크</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"faq\">FAQ</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"contact\">1:1문의</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav-right-content\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"user-profile\">MY PAGE</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"pr-0\">\r\n");
      out.write("                        <a class=\"btn btn-yellow\" href=\"tour-details\">축제 캘린더<i class=\"fa fa-paper-plane\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- navbar area end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- breadcrumb area start -->\r\n");
      out.write("    <div class=\"breadcrumb-area style-three jarallax\" style=\"background-image:url(images/bg/1.png);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-inner\">\r\n");
      out.write("                        <h1 class=\"page-title\">축제 일기</h1>\r\n");
      out.write("                        <ul class=\"page-list\">\r\n");
      out.write("                            <li><a href=\"index\">Home</a></li>\r\n");
      out.write("                            <li>내가 방문했던 축제는 ?</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- breadcrumb area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- blog area start -->\r\n");
      out.write("    <div class=\"blog-details-area pd-top-120\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <div class=\"gallery-filter-area row justify-content-center\">\r\n");
      out.write("                        <div class=\"gallery-sizer col-1\"></div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"images/blog/1.png\" alt=\"blog\">\r\n");
      out.write("                                    <a class=\"tag\" href=\"#\">New</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">2023. 01. 02.</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details02\">일기 제목 들어가는 자리입니다.</a></h4>\r\n");
      out.write("                                    <p class=\"content\">일기 내용 세 줄로 들어갈 자리입니다. 일기 내용 세 줄로 들어갈 자리입니다. 일기 내용 세 줄로 들어갈 자리입니다.</p>\r\n");
      out.write("                                    <a class=\"btn-read-more\" href=\"blog-details\"><span>더 보기<i class=\"la la-arrow-right\"></i></span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog sticky\">\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">2023. 01. 02.</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details02\">일기 제목 들어갈 자리</a></h4>\r\n");
      out.write("                                    <p class=\"content\">일기 내용 세 줄로 들어갈 자리입니다. 일기 내용 세 줄로 들어갈 자리입니다. 일기 내용 세 줄로 들어갈 자리입니다.</p>\r\n");
      out.write("                                    <p class=\"author\">BY ADMIN</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"images/blog/3.png\" alt=\"blog\">\r\n");
      out.write("                                    <a class=\"tag\" href=\"#\">Europe</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">19 September 2019</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details\">Why You Shouldnât Ride Elephants France.</a></h4>\r\n");
      out.write("                                    <p class=\"content\">Praesent eu dolor eu orci vehicula euismod. Vivamus sed sollicitudin libero, vel malesuada</p>\r\n");
      out.write("                                    <a class=\"btn-read-more\" href=\"blog-details\"><span>Read More<i class=\"la la-arrow-right\"></i></span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"images/blog/4.png\" alt=\"blog\">\r\n");
      out.write("                                    <a class=\"tag\" href=\"#\">Europe</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">19 September 2019</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details\">Duis pretium gravida enim, vel maximus</a></h4>\r\n");
      out.write("                                    <p class=\"content\">Praesent eu dolor eu orci vehicula euismod. Vivamus sed sollicitudin libero, vel malesuada</p>\r\n");
      out.write("                                    <a class=\"btn-read-more\" href=\"blog-details\"><span>Read More<i class=\"la la-arrow-right\"></i></span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"images/blog/5.png\" alt=\"blog\">\r\n");
      out.write("                                    <a class=\"tag\" href=\"#\">Europe</a>\r\n");
      out.write("                                    <div class=\"video-popup-btn style-two\">\r\n");
      out.write("                                        <a href=\"https://www.youtube.com/watch?v=c7XEhXZ_rsk\" class=\"video-play-btn mfp-iframe\" tabindex=\"0\"><i class=\"fa fa-play\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">19 September 2019</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details\">Duis pretium gravida enim</a></h4>\r\n");
      out.write("                                    <p class=\"content\">Praesent eu dolor eu orci vehicula euismod. Vivamus sed sollicitudin libero, vel malesuada</p>\r\n");
      out.write("                                    <a class=\"btn-read-more\" href=\"blog-details\"><span>Read More<i class=\"la la-arrow-right\"></i></span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"images/blog/6.png\" alt=\"blog\">\r\n");
      out.write("                                    <a class=\"tag\" href=\"#\">Europe</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">19 September 2019</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details\">Why You Shouldnât Ride Elephants France.</a></h4>\r\n");
      out.write("                                    <p class=\"content\">Praesent eu dolor eu orci vehicula euismod. Vivamus sed sollicitudin libero, vel malesuada</p>\r\n");
      out.write("                                    <a class=\"btn-read-more\" href=\"blog-details\"><span>Read More<i class=\"la la-arrow-right\"></i></span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"images/blog/7.png\" alt=\"blog\">\r\n");
      out.write("                                    <a class=\"tag\" href=\"#\">Europe</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">19 September 2019</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details\">Etiam convallis elementum sapien</a></h4>\r\n");
      out.write("                                    <p class=\"content\">Praesent eu dolor eu orci vehicula euismod. Vivamus sed sollicitudin libero, vel malesuada</p>\r\n");
      out.write("                                    <a class=\"btn-read-more\" href=\"blog-details\"><span>Read More<i class=\"la la-arrow-right\"></i></span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 col-md-6 tp-gallery-item\">\r\n");
      out.write("                            <div class=\"single-blog\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"images/blog/8.png\" alt=\"blog\">\r\n");
      out.write("                                    <a class=\"tag\" href=\"#\">Europe</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-blog-details\">\r\n");
      out.write("                                    <p class=\"date\">19 September 2019</p>\r\n");
      out.write("                                    <h4 class=\"title\"><a href=\"blog-details\">Duis porta, ligula rhoncus euismod</a></h4>\r\n");
      out.write("                                    <p class=\"content\">Praesent eu dolor eu orci vehicula euismod. Vivamus sed sollicitudin libero, vel malesuada</p>\r\n");
      out.write("                                    <a class=\"btn-read-more\" href=\"blog-details\"><span>Read More<i class=\"la la-arrow-right\"></i></span></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12  text-md-center text-left\">\r\n");
      out.write("                            <div class=\"tp-pagination text-md-center text-left d-inline-block mt-4\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a class=\"prev page-numbers\" href=\"#\"><i class=\"la la-long-arrow-left\"></i></a></li>\r\n");
      out.write("                                    <li><span class=\"page-numbers\">1</span></li>\r\n");
      out.write("                                    <li><span class=\"page-numbers current\">2</span></li>\r\n");
      out.write("                                    <li><a class=\"page-numbers\" href=\"#\">3</a></li>\r\n");
      out.write("                                    <li><a class=\"page-numbers\" href=\"#\">4</a></li>\r\n");
      out.write("                                    <li><a class=\"next page-numbers\" href=\"#\"><i class=\"la la-long-arrow-right\"></i></a></li>\r\n");
      out.write("                                </ul>                          \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 우측 사이드바  -->\r\n");
      out.write("                <div class=\"col-lg-4\"  id=\"select-category\">\r\n");
      out.write("                    <aside class=\"sidebar-area sidebar-area-4\">\r\n");
      out.write("                        <div class=\"widget widget_search bg-none pd-none\">\r\n");
      out.write("                            <form class=\"write-form\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                  <button class=\"submit-btn\" type=\"submit\" ><a href=\"destination-details02\">나의 일기 쓰러 가기</a><img src=\"images/pencil_24.png\" ></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form></br>\r\n");
      out.write("                            \r\n");
      out.write("                            <form class=\"search-form\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input type=\"text\" placeholder=\"Search\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button class=\"submit-btn\" type=\"submit\"><i class=\"ti-search\"></i></button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"widget widget_categories reviews\" >\r\n");
      out.write("                            <h2 class=\"widget-title\">이 축제 일기만 보여줘 !</h2>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><label class=\"\">지역</label></li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                	<select class=\"select-category\" name=\"select-category\">\r\n");
      out.write("                                		<option value=\"전체\">전체</option>\r\n");
      out.write("                                		<option value=\"서울\">서울</option>\r\n");
      out.write("                                		<option value=\"경기\">경기</option>\r\n");
      out.write("                                		<option value=\"인천\">인천</option>\r\n");
      out.write("                                		<option value=\"강원\">강원</option>\r\n");
      out.write("                                		<option value=\"충남\">충남</option>\r\n");
      out.write("                                		<option value=\"충북\">충북</option>\r\n");
      out.write("                                		<option value=\"대전\">대전</option>\r\n");
      out.write("                                		<option value=\"세종\">세종</option>\r\n");
      out.write("                                		<option value=\"전남\">전남</option>\r\n");
      out.write("                                		<option value=\"전북\">전북</option>\r\n");
      out.write("                                		<option value=\"광주\">광주</option>\r\n");
      out.write("                                		<option value=\"부산\">부산</option>\r\n");
      out.write("                                		<option value=\"울산\">울산</option>\r\n");
      out.write("                                		<option value=\"경남\">경남</option>\r\n");
      out.write("                                		<option value=\"경북\">경북</option>\r\n");
      out.write("                                		<option value=\"대구\">대구</option>\r\n");
      out.write("                                		<option value=\"제주\">제주</option>\r\n");
      out.write("                                	</select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><label>계절별</label></li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                	<select class=\"select-category\" name=\"select-category\">\r\n");
      out.write("                                		<option value=\"전체\">전체</option>\r\n");
      out.write("                                		<option value=\"봄\">봄</option>\r\n");
      out.write("                                		<option value=\"여름\">여름</option>\r\n");
      out.write("                                		<option value=\"가을\">가을</option>\r\n");
      out.write("                                		<option value=\"겨울\">겨울</option>\r\n");
      out.write("                                	</select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><label>분야별</label></li>\r\n");
      out.write("                                <li>\r\n");
      out.write("	                                <select class=\"select-category\" name=\"select-category\">\r\n");
      out.write("                                		<option value=\"전체\">전체</option>\r\n");
      out.write("	                                	<option value=\"문화·예술\">문화·예술</option>\r\n");
      out.write("	                                	<option value=\"민속·전통\">민속·전통</option>\r\n");
      out.write("	                                	<option value=\"인물·역사\">인물·역사</option>\r\n");
      out.write("	                                	<option value=\"자연·생태\">자연·생태</option>\r\n");
      out.write("	                                	<option value=\"교육·체험\">교육·체험</option>\r\n");
      out.write("	                                	<option value=\"스포츠·레저\">스포츠·레저</option>\r\n");
      out.write("	                                </select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><label>축제 이름</label></li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                	<input  type=\"text\" class=\"form-control?\" placeholder=\"축제명\">\r\n");
      out.write("                                	<button class=\"btn btn-yellow\" type=\"button\">검색</button>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"widget widget-recent-post\">\r\n");
      out.write("                            <h2 class=\"widget-title\">명예의 전당</h2>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img src=\"images/blog-details/12.png\" alt=\"widget\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"post-date\">게시일 23. 01. 01.</span>\r\n");
      out.write("                                            <h6 class=\"title\"><a href=\"#\">우리 사이 니가 짱먹으셈 1</a></h6>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img src=\"images/blog-details/13.png\" alt=\"widget\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"post-date\">게시일 23. 01. 02.</span>\r\n");
      out.write("                                            <h6 class=\"title\"><a href=\"#\">우리 사이 니가 짱먹으셈 2</a></h6>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img src=\"images/blog-details/14.png\" alt=\"widget\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"post-date\">게시일 23. 01. 03.</span>\r\n");
      out.write("                                            <h6 class=\"title\"><a href=\"#\">우리 사이 니가 짱먹으셈 3</a></h6>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div class=\"media\">\r\n");
      out.write("                                        <img src=\"images/blog-details/15.png\" alt=\"widget\">\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            <span class=\"post-date\">게시일 23. 01. 01.</span>\r\n");
      out.write("                                            <h6 class=\"title\"><a href=\"#\">우리 사이 니가 짱먹으셈 4</a></h6>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"widget widget_tag_cloud\">\r\n");
      out.write("                            <h2 class=\"widget-title\">인기 태그</h2>\r\n");
      out.write("                            <div class=\"tagcloud\">\r\n");
      out.write("                                <a href=\"#\">눈꽃</a>\r\n");
      out.write("                                <a href=\"#\">데이트</a>\r\n");
      out.write("                                <a href=\"#\">별빛</a>\r\n");
      out.write("                                <a href=\"#\">사랑</a>\r\n");
      out.write("                                <a href=\"#\">빙어</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 광고 배너 위치  -->\r\n");
      out.write("                            <div class=\"widget widget_tag_cloud\">\r\n");
      out.write("	                            <h2 class=\"widget-title\">광고 배너</h2>\r\n");
      out.write("	                           <a href=\"#\"><img src=\"images/others/01.png\" alt=\"img\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </aside>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- blog area End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- newslatter area Start -->\r\n");
      out.write("    <div class=\"newslatter-area pd-top-108\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"newslatter-area-wrap border-tp-solid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-3 col-lg-6 col-md-5 offset-xl-2\">\r\n");
      out.write("                        <div class=\"section-title mb-md-0\">\r\n");
      out.write("                            <h2 class=\"title\">Newsletter</h2>\r\n");
      out.write("                            <p>Sign up to receive the best offers</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-6 col-md-7 align-self-center offset-xl-1\">\r\n");
      out.write("                        <div class=\"input-group newslatter-wrap\">\r\n");
      out.write("                            <div class=\"input-group-prepend\">\r\n");
      out.write("                                <span class=\"input-group-text\"><i class=\"fa fa-envelope\"></i></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\r\n");
      out.write("                            <div class=\"input-group-append\">\r\n");
      out.write("                                <button class=\"btn btn-yellow\" type=\"button\">Subscribe</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- newslatter area End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- footer area start -->\r\n");
      out.write("    <footer class=\"footer-area\" style=\"background-image: url(images/bg/2.png);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"footer-widget widget\">\r\n");
      out.write("                        <div class=\"about_us_widget\">\r\n");
      out.write("                             <div class=\"widget-contact\">\r\n");
      out.write("                            <h4 class=\"widget-title\">Contact us</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <i class=\"fa fa-map-marker\"></i> \r\n");
      out.write("                                <span>서울특별시 금천구 가산디지털2로 한라원앤원타워 308호</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"location\"> \r\n");
      out.write("                                <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                                <span>feidear_kosmo@gmail.com</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"telephone\">\r\n");
      out.write("                                <i class=\"fa fa-phone base-color\"></i> \r\n");
      out.write("                                <span>\r\n");
      out.write("                                    +82 02-1234-5678\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <ul class=\"social-icon\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"facebook\" href=\"#\" target=\"_blank\"><i class=\"fa fa-facebook  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"twitter\" href=\"#\" target=\"_blank\"><i class=\"fa fa-twitter  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"pinterest\" href=\"#\" target=\"_blank\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copyright-inner\">\r\n");
      out.write("            <div class=\"copyright-text\">\r\n");
      out.write("                &copy; Viaje 2019 All rights reserved. Powered with <a href=\"http://zwin.io/\" target=\"_blank\"><i class=\"fa fa-heart\"></i> </a> by <a href=\"http://zwin.io/\" target=\"_blank\"><span>Zwin.</span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- footer area end -->\r\n");
      out.write("\r\n");
      out.write("	<!-- chatbot -->\r\n");
      out.write("	<div class=\"go-chatbot\">\r\n");
      out.write("		<span class=\"chatbot\" >\r\n");
      out.write("			<img src=\"images/chatbot_32.png\">\r\n");
      out.write("			<a class=\"\" type=\"button\"> 챗봇과 대화하기</a>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- back to top area start -->\r\n");
      out.write("    <div class=\"back-to-top\">\r\n");
      out.write("        <span class=\"back-top\"><i class=\"fa fa-angle-up\"></i></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- back to top area end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional plugin js -->\r\n");
      out.write("    <script src=\"js/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"js/slick.js\"></script>\r\n");
      out.write("    <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jarallax.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- main js -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
