/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-04 11:20:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668046164505L));
    _jspx_dependants.put("jar:file:/D:/springbootFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Feidear/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Viaje - Travel, Tour Booking HTML5 Template</title>\r\n");
      out.write("    <!-- favicon -->\r\n");
      out.write("    <link rel=icon href=\"images/favicon.png\" sizes=\"20x20\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional plugin css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/slick.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/swiper.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/nice-select.css\">\r\n");
      out.write("    <!-- icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/line-awesome.min.css\">\r\n");
      out.write("    <!-- main css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <!-- responsive css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- preloader area start -->\r\n");
      out.write("    <div class=\"preloader\" id=\"preloader\">\r\n");
      out.write("        <div class=\"preloader-inner\">\r\n");
      out.write("            <div class=\"spinner\">\r\n");
      out.write("                <div class=\"dot1\"></div>\r\n");
      out.write("                <div class=\"dot2\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- preloader area end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- //. sign up Popup -->\r\n");
      out.write("    <div class=\"signUp-popup login-register-popup\" id=\"signUp-popup\">\r\n");
      out.write("        <div class=\"login-register-popup-wrap\">\r\n");
      out.write("            <div class=\"row no-gutters\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"thumb\">\r\n");
      out.write("                        <img src=\"images/others/signup.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                    <div class=\"shape-thumb\">\r\n");
      out.write("                        <img src=\"images/others/signup-shape.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form class=\"login-form-wrap\">\r\n");
      out.write("                        <h4 class=\"text-center\">Sign Up</h4>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Name\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-user\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-envelope\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Password\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-lock\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label class=\"checkbox\">\r\n");
      out.write("                            <input type=\"checkbox\">\r\n");
      out.write("                            <span>Remember me</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <button class=\"btn btn-yellow w-100\">Sign Up</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sign-in-btn\">I already have an account. <a href=\"#\">Sign In</a></div> \r\n");
      out.write("                        <div class=\"social-wrap\">\r\n");
      out.write("                            <p>Or Continue With</p>\r\n");
      out.write("                            <ul class=\"social-icon\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"facebook\" href=\"#\" target=\"_blank\"><i class=\"fa fa-facebook  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"twitter\" href=\"#\" target=\"_blank\"><i class=\"fa fa-twitter  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"pinterest\" href=\"#\" target=\"_blank\"><i class=\"fa fa-pinterest\"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //. sign up Popup End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- navbar area start -->\r\n");
      out.write("    <nav class=\"navbar navbar-area navbar-expand-lg nav-style-01\">\r\n");
      out.write("        <div class=\"container nav-container\">\r\n");
      out.write("            <div class=\"responsive-mobile-menu\">\r\n");
      out.write("                <div class=\"mobile-logo\">\r\n");
      out.write("                    <a href=\"index\">\r\n");
      out.write("                        <img src=\"images/sticky-logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"navbar-toggler float-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#tp_main_menu\" \r\n");
      out.write("                    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggle-icon\">\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"nav-right-content\">\r\n");
      out.write("                    <ul class=\"pl-0\">\r\n");
      out.write("                        <li class=\"top-bar-btn-booking\">\r\n");
      out.write("                            <a class=\"btn btn-yellow\" href=\"tour-details\">Book Now <i class=\"fa fa-paper-plane\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"notification\">\r\n");
      out.write("                            <a class=\"signUp-btn\" href=\"#\">\r\n");
      out.write("                                <i class=\"fa fa-user-o\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"tp_main_menu\">\r\n");
      out.write("                <div class=\"logo-wrapper desktop-logo\">\r\n");
      out.write("                    <a href=\"index\" class=\"main-logo\">\r\n");
      out.write("                        <img src=\"images/logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"index\" class=\"sticky-logo\">\r\n");
      out.write("                        <img src=\"images/sticky-logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"navbar-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"tour-list\">축제</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a href=\"#\">커뮤니티</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                        <!-- 한솔 수정 -->\r\n");
      out.write("                            <li><a href=\"blog04\">축제일기</a></li>			\r\n");
      out.write("                            <li><a href=\"blog02\">매거진</a></li>\r\n");
      out.write("                            <li><a href=\"blog-details\">매거진 상세</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a href=\"#\">이벤트</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"blog03\">제휴 이벤트</a></li>\r\n");
      out.write("                      		<li><a href=\"destination-details\">서포터즈</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a href=\"#\">스마트 PAGE</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"user-profile\">MY 여행성향 분석</a></li>\r\n");
      out.write("                      		<li><a href=\"user-profile\">실시간 날씨</a></li>\r\n");
      out.write("                      		<li><a href=\"user-profile\">혼잡도 체크</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"faq\">FAQ</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"contact\">1:1문의</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav-right-content\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"user-profile\">MY PAGE</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"pr-0\">\r\n");
      out.write("                        <a class=\"btn btn-yellow\" href=\"tour-details\">축제 캘린더<i class=\"fa fa-paper-plane\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- navbar area end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- breadcrumb area start -->\r\n");
      out.write("    <div class=\"breadcrumb-area jarallax\" style=\"background-image:url(images/bg/1.png);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-inner\">\r\n");
      out.write("                        <h1 class=\"page-title\">일대일 문의</h1>\r\n");
      out.write("                        <ul class=\"page-list\">\r\n");
      out.write("                            <li><a href=\"index\">Home</a></li>\r\n");
      out.write("                            <li>궁금한 점을 질문해주세요!</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- breadcrumb area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- contact area End -->\r\n");
      out.write("    <div class=\"contact-area pd-top-108\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"section-title text-lg-center text-left\">\r\n");
      out.write("                        <h2 class=\"title\">Get In Touch!</h2>\r\n");
      out.write("                        <p>Vestibulum blandit viverra convallis. Pellentesque ligula urna, fermentum ut semper in, tincidunt nec dui. Morbi mauris lacus, consequat eget justo in</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-5 offset-xl-1 col-lg-6\">\r\n");
      out.write("                    <div class=\"thumb\">\r\n");
      out.write("                        <img src=\"images/others/11.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-5 col-lg-6\">\r\n");
      out.write("                    <form class=\"tp-form-wrap\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <label class=\"single-input-wrap style-two\">\r\n");
      out.write("                                    <span class=\"single-input-title\">분류</span>\r\n");
      out.write("                                    <select class=\"select-category\" name=\"select-category\">\r\n");
      out.write("                                		<option value=\"회원\">회원</option>\r\n");
      out.write("                                		<option value=\"축제\">축제</option>\r\n");
      out.write("                                		<option value=\"기타\">기타</option>\r\n");
      out.write("                                	</select>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <label class=\"single-input-wrap style-two\">\r\n");
      out.write("                                    <span class=\"single-input-title\">제목</span>\r\n");
      out.write("                                    <input type=\"text\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-12\">\r\n");
      out.write("                                <label class=\"single-input-wrap style-two\">\r\n");
      out.write("                                    <span class=\"single-input-title\">문의 내용</span>\r\n");
      out.write("                                    <textarea></textarea>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <label class=\"single-input-wrap style-two\">\r\n");
      out.write("                                    <span class=\"single-input-title\">첨부 파일</span>파일명\r\n");
      out.write("                                    <button class=\"btn btn\" id=\"search-file\">파일 찾기</button>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <a class=\"btn\" id=\"question-btn\"href=\"#\">문의하기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- contact area End -->\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("        \r\n");
      out.write("    <!-- newslatter area Start -->\r\n");
      out.write("    <div class=\"newslatter-area pd-top-108\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"newslatter-area-wrap border-tp-solid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-3 col-lg-6 col-md-5 offset-xl-2\">\r\n");
      out.write("                        <div class=\"section-title mb-md-0\">\r\n");
      out.write("                            <h2 class=\"title\">Newsletter</h2>\r\n");
      out.write("                            <p>Sign up to receive the best offers</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-lg-6 col-md-7 align-self-center offset-xl-1\">\r\n");
      out.write("                        <div class=\"input-group newslatter-wrap\">\r\n");
      out.write("                            <div class=\"input-group-prepend\">\r\n");
      out.write("                                <span class=\"input-group-text\"><i class=\"fa fa-envelope\"></i></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\r\n");
      out.write("                            <div class=\"input-group-append\">\r\n");
      out.write("                                <button class=\"btn btn-yellow\" type=\"button\">Subscribe</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- newslatter area End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- footer area start -->\r\n");
      out.write("    <footer class=\"footer-area\" style=\"background-image: url(images/bg/2.png);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"footer-widget widget\">\r\n");
      out.write("                        <div class=\"about_us_widget\">\r\n");
      out.write("                            <a href=\"index class=\"footer-logo\"> \r\n");
      out.write("                                <img src=\"images/logo.png\" alt=\"footer logo\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <p>We believe brand interaction is key in commu- nication. Real innovations and a positive customer experience are the heart of successful communication.</p>\r\n");
      out.write("                            <ul class=\"social-icon\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"facebook\" href=\"#\" target=\"_blank\"><i class=\"fa fa-facebook  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"twitter\" href=\"#\" target=\"_blank\"><i class=\"fa fa-twitter  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"pinterest\" href=\"#\" target=\"_blank\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <div class=\"footer-widget widget \">\r\n");
      out.write("                        <div class=\"widget-contact\">\r\n");
      out.write("                            <h4 class=\"widget-title\">Contact us</h4>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <i class=\"fa fa-map-marker\"></i> \r\n");
      out.write("                                <span>Manama Tower, Badda Link Road, Badda Dhaka, Bangladesh</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"location\"> \r\n");
      out.write("                                <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                                <span>travelpoint@gmail.com</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"telephone\">\r\n");
      out.write("                                <i class=\"fa fa-phone base-color\"></i> \r\n");
      out.write("                                <span>\r\n");
      out.write("                                    +088 012121240\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-2 col-md-6\">\r\n");
      out.write("                    <div class=\"footer-widget widget\">\r\n");
      out.write("                        <h4 class=\"widget-title\">Quick Link</h4>\r\n");
      out.write("                        <ul class=\"widget_nav_menu\">\r\n");
      out.write("                            <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                            <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Destination</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Tours</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <div class=\"footer-widget widget\">\r\n");
      out.write("                        <h4 class=\"widget-title\">Instagram Gallery</h4>\r\n");
      out.write("                        <ul class=\"widget-instagram-feed\">\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/instagram/1.png\" alt=\"img\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/instagram/2.png\" alt=\"img\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/instagram/3.png\" alt=\"img\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/instagram/4.png\" alt=\"img\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/instagram/5.png\" alt=\"img\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"images/instagram/6.png\" alt=\"img\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copyright-inner\">\r\n");
      out.write("            <div class=\"copyright-text\">\r\n");
      out.write("                &copy; Viaje 2019 All rights reserved. Powered with <a href=\"http://zwin.io/\" target=\"_blank\"><i class=\"fa fa-heart\"></i> </a> by <a href=\"http://zwin.io/\" target=\"_blank\"><span>Zwin.</span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- footer area end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- back to top area start -->\r\n");
      out.write("    <div class=\"back-to-top\">\r\n");
      out.write("        <span class=\"back-top\"><i class=\"fa fa-angle-up\"></i></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- back to top area end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional plugin js -->\r\n");
      out.write("    <script src=\"js/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"js/slick.js\"></script>\r\n");
      out.write("    <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jarallax.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- main js -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
