/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-04 11:12:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/springbootFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Feidear/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668046164505L));
    _jspx_dependants.put("jar:file:/D:/springbootFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Feidear/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Feidear</title>\r\n");
      out.write("    <!-- favicon -->\r\n");
      out.write("    <link rel=icon href=\"/images/favicon.png\" sizes=\"20x20\" type=\"image/png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional plugin css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/slick.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/swiper.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/jquery-ui.min.css\">\r\n");
      out.write("    <!-- icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/line-awesome.min.css\">\r\n");
      out.write("    <!-- main css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.css\">\r\n");
      out.write("    <!-- responsive css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- preloader area start -->\r\n");
      out.write("    <div class=\"preloader\" id=\"preloader\">\r\n");
      out.write("        <div class=\"preloader-inner\">\r\n");
      out.write("            <div class=\"spinner\">\r\n");
      out.write("                <div class=\"dot1\"></div>\r\n");
      out.write("                <div class=\"dot2\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- preloader area end -->\r\n");
      out.write("\r\n");
      out.write(" <div class=\"body-overlay\" id=\"body-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("    <!-- //. login Popup -->\r\n");
      out.write("    <div class=\"signUp-popup login-register-popup\" id=\"signUp-popup\">\r\n");
      out.write("        <div class=\"login-register-popup-wrap\">\r\n");
      out.write("            <div class=\"row no-gutters\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"thumb\">\r\n");
      out.write("                        <img src=\"images/others/signup.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 align-self-center\">\r\n");
      out.write("                    <div class=\"shape-thumb\">\r\n");
      out.write("                        <img src=\"images/others/signup-shape.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form class=\"login-form-wrap\">\r\n");
      out.write("                        <h4 class=\"text-center\">Log In</h4>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"ID\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-user\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Password\">\r\n");
      out.write("                            <span class=\"single-input-title\"><i class=\"fa fa-lock\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label class=\"checkbox\">\r\n");
      out.write("                            <input type=\"checkbox\">\r\n");
      out.write("                            <span>Remember me</span>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div class=\"single-input-wrap style-two\">\r\n");
      out.write("                            <button class=\"btn btn-yellow w-100\">로그인</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sign-in-btn\">페이디어 계정이 없어요 ☞ <a href=\"/sign-up2\">회원가입</a></div> \r\n");
      out.write("                        <div class=\"social-wrap\">\r\n");
      out.write("                            <p>Or Continue With</p>\r\n");
      out.write("                            <ul class=\"social-icon\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"facebook\" href=\"/#\" target=\"_blank\"><i class=\"fa fa-facebook  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a class=\"twitter\" href=\"/#\" target=\"_blank\"><i class=\"fa fa-twitter  \"></i></a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //. login Popup End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- navbar area start -->\r\n");
      out.write("    <div class=\"top-navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6 topbar-contact-wrap\">\r\n");
      out.write("                    <div class=\"topbar-contact\">\r\n");
      out.write("                        <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                        <span class=\"title\">Support :</span>\r\n");
      out.write("                        <span class=\"number\">02 1234 5678</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"social-icon\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"facebook\" href=\"/#\" target=\"_blank\"><i class=\"fa fa-facebook  \"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"twitter\" href=\"/#\" target=\"_blank\"><i class=\"fa fa-twitter  \"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"pinterest\" href=\"/#\" target=\"_blank\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"nav-right-content float-right\">\r\n");
      out.write("                        <ul class=\"pl-0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"notification\">\r\n");
      out.write("                                <a class=\"signUp-btn\" href=\"/#\">\r\n");
      out.write("                                    <i class=\"fa fa-user-o\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"navbar navbar-area navbar-expand-lg nav-style-03\">\r\n");
      out.write("        <div class=\"container nav-container\">\r\n");
      out.write("            <div class=\"responsive-mobile-menu\">\r\n");
      out.write("                <div class=\"mobile-logo\">\r\n");
      out.write("                    <a href=\"/index\">\r\n");
      out.write("                        <img src=\"images/sticky-logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"navbar-toggler float-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#tp_main_menu\" \r\n");
      out.write("                    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggle-icon\">\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                        <span class=\"line\"></span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"nav-right-content\">\r\n");
      out.write("                    <ul class=\"pl-0\">\r\n");
      out.write("                        <li class=\"top-bar-btn-booking\">\r\n");
      out.write("                            <a class=\"btn btn-yellow\" href=\"/tour-details\">Book Now <i class=\"fa fa-paper-plane\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"notification\">\r\n");
      out.write("                            <a class=\"signUp-btn\" href=\"/#\">\r\n");
      out.write("                                <i class=\"fa fa-user-o\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"tp_main_menu\">\r\n");
      out.write("                <div class=\"logo-wrapper desktop-logo\">\r\n");
      out.write("                    <a href=\"/index\" class=\"main-logo\">\r\n");
      out.write("                        <img src=\"images/logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"/index\" class=\"sticky-logo\">\r\n");
      out.write("                        <img src=\"images/sticky-logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"navbar-nav\">\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a>축제 둘러보기</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"/tour-list02\">축제 정보</a></li>\r\n");
      out.write("                            <li><a href=\"/tour-list02\">근처 맛집</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a>커뮤니티</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"/blog04\">축제 일기</a></li>\r\n");
      out.write("                            <li><a href=\"/blog02\">매거진</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a>이벤트</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"/blog03\">제휴 이벤트</a></li>\r\n");
      out.write("                      		<li><a href=\"/destination-details\">서포터즈</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"/smart-page\">스마트 페이지</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children\">\r\n");
      out.write("                        <a>문의사항</a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                            <li><a href=\"/faq\">FAQ</a></li>\r\n");
      out.write("                            <li><a href=\"/contact\">1:1 문의</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav-right-content\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"/user-profile\">MY PAGE</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"pr-0\">\r\n");
      out.write("                        <a class=\"btn btn-yellow\" href=\"/calendar\">축제 캘린더<i class=\"fa fa-paper-plane\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- navbar area end -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
