/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-04 11:04:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class promotion_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
String pjName = "/Feidear";
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- breadcrumb area start -->\r\n");
      out.write("    <div class=\"breadcrumb-area jarallax\" style=\"background-image:url(");
      out.print(pjName);
      out.write("/resources/assets/images/bg/1.png);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-inner\">\r\n");
      out.write("                        <h1 class=\"page-title\">디어유 모집</h1>\r\n");
      out.write("                        <ul class=\"page-list\">\r\n");
      out.write("                          <li>페이디어 서포터즈가 되는 방법</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- breadcrumb area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- blog area start -->\r\n");
      out.write("    <div class=\"user-profile-area pd-top-120\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-10 col-lg-12\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-4\">\r\n");
      out.write("                            <ul class=\"nav nav-tabs tp-tabs style-two\">\r\n");
      out.write("                                \r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" data-toggle=\"tab\" href=\"#tabs_3\"><i class=\"fa fa-bar-chart\" aria-hidden=\"true\"></i>디어유 모집</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                                <body>\r\n");
      out.write("                                <!-- 디어유 모집 탭-->\r\n");
      out.write("                                <div class=\"tab-pane fade\" id=\"tabs_3\">\r\n");
      out.write("                                    <div class=\"user-details\">\r\n");
      out.write("                                        <h3 class=\"user-details-title\"></h3>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                        	<div class=\"col-lg-12 bg-gray\" style=\"padding-top: 3vw;\">\r\n");
      out.write("                                        		\r\n");
      out.write("                                        		<!-- 디어유 제목 탭 -->\r\n");
      out.write("                                                <div class=\"col-lg-5\" style=\"margin: 0px auto;\">\r\n");
      out.write("                                                	<h4 style=\"text-align: center; margin-bottom: 30px;\">디어유가 되어 줘!</h4>\r\n");
      out.write("                                                	<div class=\"user-payment-card\" style=\"text-align: center;\">\r\n");
      out.write("                                                    	<img src=\"");
      out.print(pjName);
      out.write("/resources/assets/images/others/01.png\" alt=\"img\" style=\"margin-bottom: 1.25vw; border-radius: 70%\">\r\n");
      out.write("                                                        <br/>\r\n");
      out.write("                                                        \r\n");
      out.write("                                                        \r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            	<div class=\"col-lg-10 widget-contact\" style=\"margin: 0px auto;\">\r\n");
      out.write("		                                             <p>\r\n");
      out.write("		                                				<i class=\"fa fa-thumb-tack\" aria-hidden=\"true\"></i>\r\n");
      out.write("		                                				<span style=\"color: black;\">디어유란? <br> 소정의 지원금을 받고 축제를 체험한 후 <br> 양질의 후기를 나누어 주는 페이디어의 서포터즈 </span>\r\n");
      out.write("		                            				</p>\r\n");
      out.write("		                                            <p>\r\n");
      out.write("		                                				<i class=\"fa fa-thumb-tack\" aria-hidden=\"true\"></i>\r\n");
      out.write("		                                				<span style=\"color: black;\">디어유가 하는 일 <br> 막노동 <br> 사진 찍기 <br> 리뷰 올리기 </span>\r\n");
      out.write("		                            				</p>\r\n");
      out.write("		                            				<p>\r\n");
      out.write("		                                				<i class=\"fa fa-thumb-tack\" aria-hidden=\"true\"></i>\r\n");
      out.write("		                                				<span style=\"color: black;\">디어유 혜택 <br> 소정의 경비 제공 <br> 뿌듯함 <br> 관심 받을 수 있음</span>\r\n");
      out.write("		                            				</p>\r\n");
      out.write("		                            				<p>\r\n");
      out.write("		                                				<i class=\"fa fa-thumb-tack\" aria-hidden=\"true\"></i>\r\n");
      out.write("		                                				<span style=\"color: black;\">디어유가 되는 방법 <br> 아래 첨부된 파일을 다운로드 후 작성하여 email@email.com 으로 보내 주면 끝! <br> 합불 여부에 관계없이 결과 메일은 모두에게 전송됩니다</span>\r\n");
      out.write("		                            					<a class=\"btn btn-transparent\" href=\"#\" style=\"margin: 1vw;\">신청서 다운로드</a>\r\n");
      out.write("		                            				</p>\r\n");
      out.write("		                            				\r\n");
      out.write("                                            	</div>   \r\n");
      out.write("                                            	\r\n");
      out.write("                                            	<!-- 디어유 활동 내역 보기 -->\r\n");
      out.write("                                            	<div class=\"newslatter-area-wrap border-tp-solid\" >\r\n");
      out.write("                                            	<h4 style=\"text-align: center; margin-bottom: 70px;\">지난 기수 활동 구경하기</h4>\r\n");
      out.write("	                                            	<div class=\"fstv-grid\"  style=\"overflow:auto;\">\r\n");
      out.write("		                                            	<div class=\"col-lg-3\" style=\"margin: 0px auto;\">\r\n");
      out.write("		                                                	<div class=\"user-payment-card fstv-list\" style=\"text-align: center;\">\r\n");
      out.write("		                                                    	<img src=\"");
      out.print(pjName);
      out.write("/resources/assets/images/others/01.png\" alt=\"img\" style=\"margin-bottom: 1.25vw; border-radius: 70%\">\r\n");
      out.write("		                                                        <br/>\r\n");
      out.write("		                                                        <span style=\"white-space: nowrap;\"> OO축제 </span>\r\n");
      out.write("		                                                    </div>\r\n");
      out.write("		                                                </div>\r\n");
      out.write("		                                                \r\n");
      out.write("		                                            	<div class=\"col-lg-3\" style=\"margin: 0px auto;\">\r\n");
      out.write("		                                                	<div class=\"user-payment-card fstv-list\" style=\"text-align: center;\">\r\n");
      out.write("		                                                    	<img src=\"");
      out.print(pjName);
      out.write("/resources/assets/images/others/01.png\" alt=\"img\" style=\"margin-bottom: 1.25vw; border-radius: 70%\">\r\n");
      out.write("		                                                        <br/>\r\n");
      out.write("		                                                        <span style=\"white-space: nowrap;\"> OO축제 </span>\r\n");
      out.write("		                                                    </div>\r\n");
      out.write("		                                                </div>\r\n");
      out.write("		                                            	\r\n");
      out.write("		                                            	<div class=\"col-lg-3\" style=\"margin: 0px auto;\">\r\n");
      out.write("		                                                	<div class=\"user-payment-card fstv-list\" style=\"text-align: center;\">\r\n");
      out.write("		                                                    	<img src=\"");
      out.print(pjName);
      out.write("/resources/assets/images/others/01.png\" alt=\"img\" style=\"margin-bottom: 1.25vw; border-radius: 70%\">\r\n");
      out.write("		                                                        <br/>\r\n");
      out.write("		                                                        <span style=\"white-space: nowrap;\"> OO축제 </span>\r\n");
      out.write("		                                                    </div>\r\n");
      out.write("		                                                </div>\r\n");
      out.write("		                                            	\r\n");
      out.write("		                                            	<div class=\"col-lg-3\" style=\"margin: 0px auto;\">\r\n");
      out.write("		                                                	<div class=\"user-payment-card fstv-list\" style=\"text-align: center;\">\r\n");
      out.write("		                                                    	<img src=\"");
      out.print(pjName);
      out.write("/resources/assets/images/others/01.png\" alt=\"img\" style=\"margin-bottom: 1.25vw; border-radius: 70%\">\r\n");
      out.write("		                                                        <br/>\r\n");
      out.write("		                                                        <span style=\"white-space: nowrap;\"> OO축제 </span>\r\n");
      out.write("		                                                    </div>\r\n");
      out.write("		                                                </div>\r\n");
      out.write("	                                                </div>\r\n");
      out.write("                                            	</div>     \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                       	</div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- blog area End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- newslatter area Start -->\r\n");
      out.write("    <div class=\"newslatter-area pd-top-120\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- newslatter area End -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- back to top area start -->\r\n");
      out.write("    <div class=\"back-to-top\">\r\n");
      out.write("        <span class=\"back-top\"><i class=\"fa fa-angle-up\"></i></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- back to top area end -->\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Additional plugin js -->\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/slick.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/jarallax.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- main js -->\r\n");
      out.write("	<script src=\"");
      out.print(pjName);
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
