/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-04 11:02:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_002dup2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <!-- breadcrumb area start -->\r\n");
      out.write("    <div class=\"breadcrumb-area jarallax\" style=\"background-image:url(images/bg/1.png);\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb-inner\">\r\n");
      out.write("                        <h1 class=\"page-title\">Sign Up</h1>\r\n");
      out.write("                        <ul class=\"page-list\"><br/>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- breadcrumb area End -->\r\n");
      out.write("\r\n");
      out.write("    <!--  Form area Start -->\r\n");
      out.write("    <div class=\"contact-area pd-top-108\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"section-title text-lg-center text-left\">\r\n");
      out.write("                        <h2 class=\"title\">[ 회원가입 ]</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><br><br>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-5 offset-xl-1 col-lg-6\">\r\n");
      out.write("                    <div class=\"thumb\">\r\n");
      out.write("                        <img src=\"images/others/11.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"thumb\">\r\n");
      out.write("                        <img src=\"images/others/11.png\" alt=\"img\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                			<div class=\"col-xl-3 col-lg-4\">\r\n");
      out.write("                        	    <div class=\"wrapper\">\r\n");
      out.write("							         <div class=\"title\"><h1 style=\"font-size: 28px; color: #FF8C00\">페이디어의 회원이 되어주세요!</h1></div><br><br>\r\n");
      out.write("							        \r\n");
      out.write("							        	<!-- 이름 -->\r\n");
      out.write("								        <div class=\"u_name\">\r\n");
      out.write("									        <label class=\"single-input-wrap style-two\">\r\n");
      out.write("									            <input id=\"name\" type=\"text\" placeholder=\"이름을 입력해 주세요.\">\r\n");
      out.write("									        </label>\r\n");
      out.write("								        </div><br>\r\n");
      out.write("								        \r\n");
      out.write("							        	<!-- 이메일 -->\r\n");
      out.write("								        <div class=\"email\">\r\n");
      out.write("									        <label class=\"single-input-wrap style-two\">\r\n");
      out.write("									            <input id=\"email\" type=\"text\" placeholder=\"이메일을 입력해 주세요.\">\r\n");
      out.write("									            <div id=\"emailError\" class=\"error\"></div>\r\n");
      out.write("									        </label>\r\n");
      out.write("								        </div><br>\r\n");
      out.write("								        \r\n");
      out.write("								        <!-- 아이디 -->\r\n");
      out.write("								        <div class=\"name\">\r\n");
      out.write("								        	<label class=\"single-input-wrap style-two\">\r\n");
      out.write("									            <input id=\"name\"  type=\"text\" placeholder=\"아이디를 입력해 주세요.\">\r\n");
      out.write("									            <div id=\"nameError\" class=\"error\"></div>\r\n");
      out.write("								        	</label>\r\n");
      out.write("								        </div><br>\r\n");
      out.write("							        \r\n");
      out.write("								        <!-- 비밀번호 & 유효성 검사 -->\r\n");
      out.write("								        <div class=\"password\">\r\n");
      out.write("								       		<label class=\"single-input-wrap style-two\">\r\n");
      out.write("									            <input id=\"password\" type=\"password\" placeholder=\"비밀번호를 입력해 주세요.\">\r\n");
      out.write("									            <div id=\"passwordError\" class=\"error\"></div>\r\n");
      out.write("								            </label>\r\n");
      out.write("								        </div><br>\r\n");
      out.write("							        \r\n");
      out.write("								        <div class=\"passwordCheck\">\r\n");
      out.write("								        	<label class=\"single-input-wrap style-two\">\r\n");
      out.write("									            <input id=\"passwordCheck\" type=\"password\" placeholder=\"비밀번호를 다시 입력해 주세요.\">\r\n");
      out.write("									            <div id=\"passwordCheckError\" class=\"error\"></div>\r\n");
      out.write("								            </label>\r\n");
      out.write("								        </div><br>\r\n");
      out.write("								        \r\n");
      out.write("								    <div class=\"line\"><hr></div><br/>\r\n");
      out.write("								     \r\n");
      out.write("								     <!--  \r\n");
      out.write("							        <div class=\"area\">\r\n");
      out.write("							            <select id=\"area\">\r\n");
      out.write("							                <option selected disabled>내 지역 선택</option>\r\n");
      out.write("							                	<option value=\"#서울\">서울</option>\r\n");
      out.write("			                                    <option value=\"#강원\">강원</option>\r\n");
      out.write("			                                    <option value=\"#경기\">경기</option>\r\n");
      out.write("			                                    <option value=\"#경남\">경남</option>\r\n");
      out.write("			                                    <option value=\"#경북\">경북</option>\r\n");
      out.write("			                                    <option value=\"#광주\">광주</option>\r\n");
      out.write("			                                    <option value=\"#대구\">대구</option>\r\n");
      out.write("			                                    <option value=\"#대전\">대전</option>\r\n");
      out.write("			                                    <option value=\"#부산\">부산</option>\r\n");
      out.write("			                                    <option value=\"#세종\">세종</option>\r\n");
      out.write("			                                    <option value=\"#울산\">울산</option>\r\n");
      out.write("			                                    <option value=\"#인천\">인천</option>\r\n");
      out.write("			                                    <option value=\"#전남\">전남</option>\r\n");
      out.write("			                                    <option value=\"#전북\">전북</option>\r\n");
      out.write("			                                    <option value=\"#제주\">제주</option>\r\n");
      out.write("			                                    <option value=\"#충남\">충남</option>\r\n");
      out.write("			                                    <option value=\"#충북\">충북</option>\r\n");
      out.write("			                                    <option value=\"#온라\">온라인</option>\r\n");
      out.write("							            </select>\r\n");
      out.write("							            <div id=\"areaError\" class=\"error\"></div>\r\n");
      out.write("							        </div><br>-->  \r\n");
      out.write("							        \r\n");
      out.write("							        <div class=\"user_type\"> <!-- gender -->\r\n");
      out.write("							            <input id=\"normal_user\" type=\"radio\" name=\"user\">&nbsp&nbsp일반 회원 \r\n");
      out.write("							            &nbsp&nbsp&nbsp&nbsp<input id=\"fstv_user\" type=\"radio\" name=\"user\">&nbsp&nbsp축제 관계자\r\n");
      out.write("							        </div><br>\r\n");
      out.write("							        \r\n");
      out.write("							        <div class=\"line\"><hr></div><br/>\r\n");
      out.write("							        \r\n");
      out.write("							        <div class=\"input-group-append\">\r\n");
      out.write("							        	<div class=\"signUp\">\r\n");
      out.write("                                			<button id=\"signUpButton\" class=\"btn btn-yellow\" type=\"button\" disabled onclick=\"signUpCheck()\">가입하기</button>\r\n");
      out.write("                                		</div>\r\n");
      out.write("                            		</div>\r\n");
      out.write("							    </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    <!-- Form area End -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- 빈 여백 -->\r\n");
      out.write("    <!-- newslatter area Start -->\r\n");
      out.write("    <div class=\"newslatter-area pd-top-108\">\r\n");
      out.write("    <div><br><br><br></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- newslatter area End -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Additional plugin js -->\r\n");
      out.write("    <script src=\"js/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"js/slick.js\"></script>\r\n");
      out.write("    <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jarallax.min.js\"></script>\r\n");
      out.write("    <script src=\"js/signup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- main js -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
