/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-04 11:16:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668046164505L));
    _jspx_dependants.put("jar:file:/D:/springbootFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Feidear/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
String pjName = "/Feidear";
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <!-- Meta, title, CSS, favicons, etc. -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/ico\" />\r\n");
      out.write("\r\n");
      out.write("    <title>FeiDear Admin</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"vendors/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"vendors/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- NProgress -->\r\n");
      out.write("    <link href=\"vendors/nprogress/nprogress.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- iCheck -->\r\n");
      out.write("    <link href=\"vendors/iCheck/skins/flat/green.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("    <!-- bootstrap-progressbar -->\r\n");
      out.write("    <link href=\"vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- JQVMap -->\r\n");
      out.write("    <link href=\"vendors/jqvmap/dist/jqvmap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <!-- bootstrap-daterangepicker -->\r\n");
      out.write("    <link href=\"vendors/bootstrap-daterangepicker/daterangepicker.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme Style -->\r\n");
      out.write("    <link href=\"build/css/custom.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("		@font-face {\r\n");
      out.write("			font-family: 'TmoneyRoundWindRegular';\r\n");
      out.write("			src:\r\n");
      out.write("				url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/TmoneyRoundWindRegular.woff')\r\n");
      out.write("				format('woff');\r\n");
      out.write("			font-weight: normal;\r\n");
      out.write("			font-style: normal;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"nav-md\" style=\"font-family: TmoneyRoundWindRegular\">\r\n");
      out.write("    <div class=\"container body\">\r\n");
      out.write("      <div class=\"main_container\">\r\n");
      out.write("      	\r\n");
      out.write("      	<!-- 사이드바 메뉴 시작 -->\r\n");
      out.write("        <div class=\"col-md-3 left_col\">\r\n");
      out.write("          <div class=\"left_col scroll-view\">\r\n");
      out.write("          \r\n");
      out.write("          	<!-- 대시보드(어드민 인덱스) 이동 -->\r\n");
      out.write("            <div class=\"navbar nav_title\">\r\n");
      out.write("              <a href=\"index\" class=\"site_title\"><i class=\"fa fa-lightbulb-o\"   style=\"border: 0;\"></i> <span>FeiDear Admin</span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 어드민 사이드 메뉴 이동 -->\r\n");
      out.write("            <div id=\"sidebar-menu\" class=\"main_menu_side hidden-print main_menu\">\r\n");
      out.write("              <div class=\"menu_section\">\r\n");
      out.write("                <ul class=\"nav side-menu\">\r\n");
      out.write("                  <li><a href=\"../index\"><i class=\"fa fa-arrow-circle-right\" aria-hidden=\"true\"></i>사용자 페이지 이동</a></li>\r\n");
      out.write("                  <li><a><i class=\"fa fa-trophy\"></i>축제 관리<span class=\"fa fa-chevron-down\"></span></a>\r\n");
      out.write("                    <ul class=\"nav child_menu\">\r\n");
      out.write("                      <li><a href=\"manageFestivals\">축제 목록</a></li>\r\n");
      out.write("                      <li><a href=\"insertFestival\">축제 등록</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li><a href=\"manageUsers\"><i class=\"fa fa-users\"></i>회원 관리</a></li>\r\n");
      out.write("                  <li><a href=\"communityAdmin\"><i class=\"fa fa-comments\"></i>커뮤니티 관리</a></li>\r\n");
      out.write("                  <li><a href=\"manageQnA\"><i class=\"fa fa-question-circle\"></i>문의사항 관리</a></li>\r\n");
      out.write("                  <li><a href=\"eventAdmin\"><i class=\"fa fa-calendar-check-o\"></i>이벤트 관리</a></li>\r\n");
      out.write("                  \r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /sidebar menu -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("		<!-- 사이드바 메뉴 끝 -->\r\n");
      out.write("		\r\n");
      out.write("        <!-- top navigation -->\r\n");
      out.write("        <div class=\"top_nav\">\r\n");
      out.write("          <div class=\"nav_menu\">\r\n");
      out.write("              <div class=\"nav toggle\">\r\n");
      out.write("                <a id=\"menu_toggle\" style=\"padding : 15px 15px 15px;\"><i class=\"fa fa-bars\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <nav class=\"nav navbar-nav\">\r\n");
      out.write("              \r\n");
      out.write("            </nav>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /top navigation -->\r\n");
      out.write("\r\n");
      out.write("        <!-- page content -->\r\n");
      out.write("        <div class=\"right_col\" role=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          <br />\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4 \">\r\n");
      out.write("              <div class=\"x_panel tile fixed_height_320\" style=\"border-radius:15px;\">\r\n");
      out.write("                <div class=\"x_title\">\r\n");
      out.write("                  <h2>연령대 분석</h2>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <table class=\"\" style=\"width:100%\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th style=\"width:37%;\">\r\n");
      out.write("                        <p>Top 5</p>\r\n");
      out.write("                      </th>\r\n");
      out.write("                      <th>\r\n");
      out.write("                        <div class=\"col-lg-7 col-md-7 col-sm-7 \">\r\n");
      out.write("                          <p class=\"\">Device</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-5 col-md-5 col-sm-5 \">\r\n");
      out.write("                          <p class=\"\">Progress</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <canvas class=\"canvasDoughnut\" height=\"140\" width=\"140\" style=\"margin: 15px 10px 10px 0\"></canvas>\r\n");
      out.write("                      </td>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <table class=\"tile_info\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square blue\"></i>IOS </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>30%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square green\"></i>Android </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>10%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square purple\"></i>Blackberry </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>20%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square aero\"></i>Symbian </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>15%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square red\"></i>Others </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>30%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                </div> \r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4 \">\r\n");
      out.write("              <div class=\"x_panel tile fixed_height_320 overflow_hidden\" style=\"border-radius:15px;\">\r\n");
      out.write("                <div class=\"x_title\">\r\n");
      out.write("                  <h2>조회수 TOP3</h2>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <table class=\"\" style=\"width:100%\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th style=\"width:37%;\">\r\n");
      out.write("                        <p>Top 5</p>\r\n");
      out.write("                      </th>\r\n");
      out.write("                      <th>\r\n");
      out.write("                        <div class=\"col-lg-7 col-md-7 col-sm-7 \">\r\n");
      out.write("                          <p class=\"\">Device</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-5 col-md-5 col-sm-5 \">\r\n");
      out.write("                          <p class=\"\">Progress</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <canvas class=\"canvasDoughnut\" height=\"140\" width=\"140\" style=\"margin: 15px 10px 10px 0\"></canvas>\r\n");
      out.write("                      </td>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <table class=\"tile_info\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square blue\"></i>IOS </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>30%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square green\"></i>Android </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>10%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square purple\"></i>Blackberry </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>20%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square aero\"></i>Symbian </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>15%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                              <p><i class=\"fa fa-square red\"></i>Others </p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>30%</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4 \">\r\n");
      out.write("              <div class=\"x_panel tile fixed_height_320\" style=\"border-radius:15px;\">\r\n");
      out.write("                <div class=\"x_title\">\r\n");
      out.write("                  <h2>방문자 수</h2>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <div class=\"dashboard-widget-content\">\r\n");
      out.write("                    <ul class=\"quick-list\">\r\n");
      out.write("                      <li><i class=\"fa fa-calendar-o\"></i><a href=\"#\">Settings</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-bars\"></i><a href=\"#\">Subscription</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-bar-chart\"></i><a href=\"#\">Auto Renewal</a> </li>\r\n");
      out.write("                      <li><i class=\"fa fa-line-chart\"></i><a href=\"#\">Achievements</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-bar-chart\"></i><a href=\"#\">Auto Renewal</a> </li>\r\n");
      out.write("                      <li><i class=\"fa fa-line-chart\"></i><a href=\"#\">Achievements</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><i class=\"fa fa-area-chart\"></i><a href=\"#\">Logout</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"sidebar-widget\">\r\n");
      out.write("                        <h4>Profile Completion</h4>\r\n");
      out.write("                        <canvas width=\"150\" height=\"80\" id=\"chart_gauge_01\" class=\"\" style=\"width: 160px; height: 100px;\"></canvas>\r\n");
      out.write("                        <div class=\"goal-wrapper\">\r\n");
      out.write("                          <span id=\"gauge-text\" class=\"gauge-value pull-left\">0</span>\r\n");
      out.write("                          <span class=\"gauge-value pull-left\">%</span>\r\n");
      out.write("                          <span id=\"goal-text\" class=\"goal-value pull-right\">100%</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4 col-sm-4 \">\r\n");
      out.write("              <div class=\"x_panel\" style=\"border-radius:15px;\">\r\n");
      out.write("                <div class=\"x_title\">\r\n");
      out.write("                  <h2>달력 클릭 수 <small>Sessions</small></h2>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <h4>App Usage across versions</h4>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.2</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 66%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>123k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.3</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 45%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>53k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.4</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 25%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>23k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.5</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 5%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>3k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>0.1.5.6</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 2%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_right w_20\">\r\n");
      out.write("                      <span>1k</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>      \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-8 col-sm-8 \">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<!-- start 가입유저수 -->\r\n");
      out.write("                <div class=\"col-md-12 col-sm-12 \">\r\n");
      out.write("                  <div class=\"x_panel\" style=\"border-radius:15px;\">\r\n");
      out.write("                    <div class=\"x_title\">\r\n");
      out.write("                      <h2>가입 유저 수</h2>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"clearfix\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("						<div class=\"col-md-12 col-sm-12 \">\r\n");
      out.write("                  			<div id=\"chart_plot_01\" class=\"demo-placeholder\"></div>\r\n");
      out.write("                		</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("				<!-- end 가입유저수 -->\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("                <!-- Start 리뷰수 -->\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-sm-6 \">\r\n");
      out.write("                  <div class=\"x_panel\" style=\"border-radius:15px;\">\r\n");
      out.write("                    <div class=\"x_title\">\r\n");
      out.write("                      <h2>리뷰 수</h2>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"clearfix\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      \r\n");
      out.write("                    <h2>Bar graph <small>Sessions</small></h2>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"x_content\">\r\n");
      out.write("                    <canvas id=\"mybarChart\"></canvas>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- end 리뷰수 -->\r\n");
      out.write("                \r\n");
      out.write("                <!-- start of weather widget -->\r\n");
      out.write("                <div class=\"col-md-6 col-sm-6 \">\r\n");
      out.write("                  <div class=\"x_panel\" style=\"border-radius:15px;\">\r\n");
      out.write("                    <div class=\"x_title\">\r\n");
      out.write("                  <h2>매거진 조회 수 <small>Sessions</small></h2>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"clearfix\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"x_content\">\r\n");
      out.write("                  <h4>App Usage across versions</h4>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>11월</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 66%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("	                    <div class=\"w_right w_20\">\r\n");
      out.write("	                      <span>123k</span>\r\n");
      out.write("	                    </div>\r\n");
      out.write("                  	</div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>12월</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 66%;\">\r\n");
      out.write("                          <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("	                    <div class=\"w_right w_20\">\r\n");
      out.write("	                      <span>123k</span>\r\n");
      out.write("	                    </div>\r\n");
      out.write("                  	</div>\r\n");
      out.write("                  <div class=\"widget_summary\">\r\n");
      out.write("                    <div class=\"w_left w_25\">\r\n");
      out.write("                      <span>1월</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"w_center w_55\">\r\n");
      out.write("                      <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar bg-green\" role=\"progressbar\" aria-valuenow=\"30\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 29%;\">\r\n");
      out.write("                          <span class=\"sr-only\">30% Complete</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("	                    <div class=\"w_right w_20\">\r\n");
      out.write("	                      <span>61k</span>\r\n");
      out.write("	                    </div>\r\n");
      out.write("                  	</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- end of weather widget -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /page content -->\r\n");
      out.write("\r\n");
      out.write("        <!-- footer content -->\r\n");
      out.write("        <footer>\r\n");
      out.write("          <div class=\"pull-right\">\r\n");
      out.write("            Gentelella - Bootstrap Admin Template by <a href=\"https://colorlib.com\">Colorlib</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearfix\"></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- /footer content -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"vendors/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <script src=\"vendors/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- FastClick -->\r\n");
      out.write("    <script src=\"vendors/fastclick/lib/fastclick.js\"></script>\r\n");
      out.write("    <!-- NProgress -->\r\n");
      out.write("    <script src=\"vendors/nprogress/nprogress.js\"></script>\r\n");
      out.write("    <!-- Chart.js -->\r\n");
      out.write("    <script src=\"vendors/Chart.js/dist/Chart.min.js\"></script>\r\n");
      out.write("    <!-- gauge.js -->\r\n");
      out.write("    <script src=\"vendors/gauge.js/dist/gauge.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap-progressbar -->\r\n");
      out.write("    <script src=\"vendors/bootstrap-progressbar/bootstrap-progressbar.min.js\"></script>\r\n");
      out.write("    <!-- iCheck -->\r\n");
      out.write("    <script src=\"vendors/iCheck/icheck.min.js\"></script>\r\n");
      out.write("    <!-- Skycons -->\r\n");
      out.write("    <script src=\"vendors/skycons/skycons.js\"></script>\r\n");
      out.write("    <!-- Flot -->\r\n");
      out.write("    <script src=\"vendors/Flot/jquery.flot.js\"></script>\r\n");
      out.write("    <script src=\"vendors/Flot/jquery.flot.pie.js\"></script>\r\n");
      out.write("    <script src=\"vendors/Flot/jquery.flot.time.js\"></script>\r\n");
      out.write("    <script src=\"vendors/Flot/jquery.flot.stack.js\"></script>\r\n");
      out.write("    <script src=\"vendors/Flot/jquery.flot.resize.js\"></script>\r\n");
      out.write("    <!-- Flot plugins -->\r\n");
      out.write("    <script src=\"vendors/flot.orderbars/js/jquery.flot.orderBars.js\"></script>\r\n");
      out.write("    <script src=\"vendors/flot-spline/js/jquery.flot.spline.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/flot.curvedlines/curvedLines.js\"></script>\r\n");
      out.write("    <!-- DateJS -->\r\n");
      out.write("    <script src=\"vendors/DateJS/build/date.js\"></script>\r\n");
      out.write("    <!-- JQVMap -->\r\n");
      out.write("    <script src=\"vendors/jqvmap/dist/jquery.vmap.js\"></script>\r\n");
      out.write("    <script src=\"vendors/jqvmap/dist/maps/jquery.vmap.world.js\"></script>\r\n");
      out.write("    <script src=\"vendors/jqvmap/examples/js/jquery.vmap.sampledata.js\"></script>\r\n");
      out.write("    <!-- bootstrap-daterangepicker -->\r\n");
      out.write("    <script src=\"vendors/moment/min/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"vendors/bootstrap-daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme Scripts -->\r\n");
      out.write("    <script src=\"build/js/custom.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
