/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-04 11:16:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manageFestivals_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668046164505L));
    _jspx_dependants.put("jar:file:/D:/springbootFinal/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Feidear/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String pjName = "/Feidear";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- Meta, title, CSS, favicons, etc. -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"icon\"\r\n");
      out.write("	href=\"images/favicon.ico\"\r\n");
      out.write("	type=\"image/ico\" />\r\n");
      out.write("\r\n");
      out.write("<title>FeiDear Admin | 축제 관리</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"vendors/bootstrap/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"vendors/font-awesome/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- NProgress -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"vendors/nprogress/nprogress.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- iCheck -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"vendors/iCheck/skins/flat/green.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap-progressbar -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- JQVMap -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"vendors/jqvmap/dist/jqvmap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- bootstrap-daterangepicker -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"vendors/bootstrap-daterangepicker/daterangepicker.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Theme Style -->\r\n");
      out.write("<link href=\"build/css/custom.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: 'TmoneyRoundWindRegular';\r\n");
      out.write("	src:\r\n");
      out.write("		url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/TmoneyRoundWindRegular.woff')\r\n");
      out.write("		format('woff');\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"nav-md\" style=\"font-family: TmoneyRoundWindRegular\">\r\n");
      out.write("	<div class=\"container body\">\r\n");
      out.write("		<div class=\"main_container\">\r\n");
      out.write("\r\n");
      out.write("			<!-- 사이드바 메뉴 시작 -->\r\n");
      out.write("			<div class=\"col-md-3 left_col\">\r\n");
      out.write("				<div class=\"left_col scroll-view\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 대시보드(어드민 인덱스) 이동 -->\r\n");
      out.write("					<div class=\"navbar nav_title\">\r\n");
      out.write("						<a href=\"index\" class=\"site_title\"><i\r\n");
      out.write("							class=\"fa fa-lightbulb-o\" style=\"border: 0;\"></i> <span>FeiDear\r\n");
      out.write("								Admin</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 어드민 사이드 메뉴 이동 -->\r\n");
      out.write("					<div id=\"sidebar-menu\"\r\n");
      out.write("						class=\"main_menu_side hidden-print main_menu\">\r\n");
      out.write("						<div class=\"menu_section\">\r\n");
      out.write("							<ul class=\"nav side-menu\">\r\n");
      out.write("								<li><a href=\"../index\"><i\r\n");
      out.write("										class=\"fa fa-arrow-circle-right\" aria-hidden=\"true\"></i>사용자\r\n");
      out.write("										페이지 이동</a></li>\r\n");
      out.write("								<li><a><i class=\"fa fa-trophy\"></i>축제 관리<span\r\n");
      out.write("										class=\"fa fa-chevron-down\"></span></a>\r\n");
      out.write("									<ul class=\"nav child_menu\">\r\n");
      out.write("										<li><a href=\"manageFestivals\">축제 목록</a></li>\r\n");
      out.write("										<li><a href=\"insertFestival\">축제 등록</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a href=\"manageUsers\"><i class=\"fa fa-users\"></i>회원\r\n");
      out.write("										관리</a></li>\r\n");
      out.write("								<li><a href=\"communityAdmin\"><i class=\"fa fa-comments\"></i>커뮤니티\r\n");
      out.write("										관리</a></li>\r\n");
      out.write("										<li><a href=\"manageQnA\"><i\r\n");
      out.write("										class=\"fa fa-question-circle\"></i>문의사항 관리</a></li>\r\n");
      out.write("								<li><a href=\"eventAdmin\"><i\r\n");
      out.write("										class=\"fa fa-calendar-check-o\"></i>이벤트 관리</a></li>\r\n");
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- /sidebar menu -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 사이드바 메뉴 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- 상단바 시작 -->\r\n");
      out.write("			<!-- top navigation -->\r\n");
      out.write("			<div class=\"top_nav\">\r\n");
      out.write("				<div class=\"nav_menu\">\r\n");
      out.write("					<div class=\"nav toggle\">\r\n");
      out.write("						<a id=\"menu_toggle\"><i class=\"fa fa-bars\"></i></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<nav class=\"nav navbar-nav\">\r\n");
      out.write("						<ul class=\" navbar-right\">\r\n");
      out.write("							<li class=\"nav-item dropdown open\" style=\"padding-left: 15px;\">\r\n");
      out.write("								<a href=\"javascript:;\" class=\"user-profile dropdown-toggle\"\r\n");
      out.write("								aria-haspopup=\"true\" id=\"navbarDropdown\" data-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\"> <img\r\n");
      out.write("									src=\"images/img.jpg\" alt=\"\">John\r\n");
      out.write("									Doe\r\n");
      out.write("							</a>\r\n");
      out.write("								<div class=\"dropdown-menu dropdown-usermenu pull-right\"\r\n");
      out.write("									aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("									<a class=\"dropdown-item\" href=\"javascript:;\"> 프로필</a> <a\r\n");
      out.write("										class=\"dropdown-item\" href=\"javascript:;\"> <span\r\n");
      out.write("										class=\"badge bg-red pull-right\">50%</span> <span>Settings</span>\r\n");
      out.write("									</a> <a class=\"dropdown-item\" href=\"javascript:;\">Help</a> <a\r\n");
      out.write("										class=\"dropdown-item\" href=\"login.html\"><i\r\n");
      out.write("										class=\"fa fa-sign-out pull-right\"></i> Log Out</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("\r\n");
      out.write("							<li role=\"presentation\" class=\"nav-item dropdown open\"><a\r\n");
      out.write("								href=\"javascript:;\" class=\"dropdown-toggle info-number\"\r\n");
      out.write("								id=\"navbarDropdown1\" data-toggle=\"dropdown\"\r\n");
      out.write("								aria-expanded=\"false\"> <i class=\"fa fa-envelope-o\"></i> <span\r\n");
      out.write("									class=\"badge bg-green\">6</span>\r\n");
      out.write("							</a>\r\n");
      out.write("								<ul class=\"dropdown-menu list-unstyled msg_list\" role=\"menu\"\r\n");
      out.write("									aria-labelledby=\"navbarDropdown1\">\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"dropdown-item\"> <span\r\n");
      out.write("											class=\"image\"><img src=\"images/img.jpg\"\r\n");
      out.write("												alt=\"Profile Image\" /></span> <span> <span>John\r\n");
      out.write("													Smith</span> <span class=\"time\">3 mins ago</span>\r\n");
      out.write("										</span> <span class=\"message\"> Film festivals used to be\r\n");
      out.write("												do-or-die moments for movie makers. They were where... </span>\r\n");
      out.write("									</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"dropdown-item\"> <span\r\n");
      out.write("											class=\"image\"><img src=\"images/img.jpg\"\r\n");
      out.write("												alt=\"Profile Image\" /></span> <span> <span>John\r\n");
      out.write("													Smith</span> <span class=\"time\">3 mins ago</span>\r\n");
      out.write("										</span> <span class=\"message\"> Film festivals used to be\r\n");
      out.write("												do-or-die moments for movie makers. They were where... </span>\r\n");
      out.write("									</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"dropdown-item\"> <span\r\n");
      out.write("											class=\"image\"><img src=\"images/img.jpg\"\r\n");
      out.write("												alt=\"Profile Image\" /></span> <span> <span>John\r\n");
      out.write("													Smith</span> <span class=\"time\">3 mins ago</span>\r\n");
      out.write("										</span> <span class=\"message\"> Film festivals used to be\r\n");
      out.write("												do-or-die moments for movie makers. They were where... </span>\r\n");
      out.write("									</a></li>\r\n");
      out.write("									<li class=\"nav-item\"><a class=\"dropdown-item\"> <span\r\n");
      out.write("											class=\"image\"><img src=\"images/img.jpg\"\r\n");
      out.write("												alt=\"Profile Image\" /></span> <span> <span>John\r\n");
      out.write("													Smith</span> <span class=\"time\">3 mins ago</span>\r\n");
      out.write("										</span> <span class=\"message\"> Film festivals used to be\r\n");
      out.write("												do-or-die moments for movie makers. They were where... </span>\r\n");
      out.write("									</a></li>\r\n");
      out.write("									<li class=\"nav-item\">\r\n");
      out.write("										<div class=\"text-center\">\r\n");
      out.write("											<a class=\"dropdown-item\"> <strong>See All Alerts</strong>\r\n");
      out.write("												<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("											</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /top navigation -->\r\n");
      out.write("			<!-- 상단바 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- 본문 내용 -->\r\n");
      out.write("			<!-- page content -->\r\n");
      out.write("			<div class=\"right_col\" role=\"main\">\r\n");
      out.write("				<div class=\"row\"\r\n");
      out.write("					style=\"text-align: center; width: 100%; margin: 0px auto;\">\r\n");
      out.write("					<br>\r\n");
      out.write("					<h2\r\n");
      out.write("						style=\"margin: 20px auto; font-size: 40px; font-weight: bolder; white-space: nowrap;\">축제\r\n");
      out.write("						목록</h2>\r\n");
      out.write("					<!-- 간편 리뷰 테이블 -->\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("						<table class=\"table\" id=\"sReviewTbl\"\r\n");
      out.write("							style=\"font-size: 1.3vw; white-space: nowrap;\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th class=\"column-title\"\r\n");
      out.write("										style=\"text-align: center; border-top: none;\">축제 이름</th>\r\n");
      out.write("									<th class=\"column-title\"\r\n");
      out.write("										style=\"text-align: center; border-top: none;\">시작일</th>\r\n");
      out.write("									<th class=\"column-title\"\r\n");
      out.write("										style=\"text-align: center; border-top: none;\">종료일</th>\r\n");
      out.write("									<th class=\"column-title\"\r\n");
      out.write("										style=\"text-align: center; border-top: none;\">지역</th>\r\n");
      out.write("									<th class=\"column-title\"\r\n");
      out.write("										style=\"text-align: center; border-top: none;\">진행 상태</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<!-- 테이블 데이터 출력 -->\r\n");
      out.write("								<!-- 상세 보기 열의 보기 클릭하면 상세 정보 수정/삭제 창으로 연결 -->\r\n");
      out.write("								<tr class=\"even pointer\">\r\n");
      out.write("									<td class=\" \"><a href=\"#\">2023 서울 아시테지 겨울축제</a></td>\r\n");
      out.write("									<td class=\" \">2023.01.02</td>\r\n");
      out.write("									<td class=\" \">2023.01.24</td>\r\n");
      out.write("									<td class=\" \">서울</td>\r\n");
      out.write("									<td class=\" \"><span class=\"badge bg-green\">진행 전</span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"odd pointer\">\r\n");
      out.write("									<td class=\" \"><a href=\"#\">2023 서울 아시테지 겨울축제</a></td>\r\n");
      out.write("									<td class=\" \">2023.01.02</td>\r\n");
      out.write("									<td class=\" \">2023.01.24</td>\r\n");
      out.write("									<td class=\" \">서울</td>\r\n");
      out.write("									<td class=\" \"><span class=\"badge badge-danger\">진행 중</span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"even pointer\">\r\n");
      out.write("									<td class=\" \">2023 서울</td>\r\n");
      out.write("									<td class=\" \">2023.01.02</td>\r\n");
      out.write("									<td class=\" \">2023.01.24</td>\r\n");
      out.write("									<td class=\" \">서울</td>\r\n");
      out.write("									<td class=\" \"><span class=\"badge badge-dark\">종료</span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"odd pointer\">\r\n");
      out.write("									<td class=\" \">2023 서울 아시테지 겨울축제 더 긴 이름</td>\r\n");
      out.write("									<td class=\" \">2023.01.02</td>\r\n");
      out.write("									<td class=\" \">2023.01.24</td>\r\n");
      out.write("									<td class=\" \">서울</td>\r\n");
      out.write("									<td class=\" \"><span class=\"badge badge-secondary\">취소</span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr class=\"even pointer\">\r\n");
      out.write("									<td class=\" \">2023 서울 아시테지 겨울축제 더 더 더 더 더 긴 이름</td>\r\n");
      out.write("									<td class=\" \">2023.01.02</td>\r\n");
      out.write("									<td class=\" \">2023.01.24</td>\r\n");
      out.write("									<td class=\" \">서울</td>\r\n");
      out.write("									<td class=\" \"><span class=\"badge badge-warning\">미정</span></td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /page content -->\r\n");
      out.write("\r\n");
      out.write("			<!-- footer content -->\r\n");
      out.write("			<footer>\r\n");
      out.write("				<div class=\"pull-right\">FeiDear</div>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("			</footer>\r\n");
      out.write("			<!-- /footer content -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("	<!-- Bootstrap -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- FastClick -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/fastclick/lib/fastclick.js\"></script>\r\n");
      out.write("	<!-- NProgress -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/nprogress/nprogress.js\"></script>\r\n");
      out.write("	<!-- Chart.js -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/Chart.js/dist/Chart.min.js\"></script>\r\n");
      out.write("	<!-- gauge.js -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/gauge.js/dist/gauge.min.js\"></script>\r\n");
      out.write("	<!-- bootstrap-progressbar -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/bootstrap-progressbar/bootstrap-progressbar.min.js\"></script>\r\n");
      out.write("	<!-- iCheck -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/iCheck/icheck.min.js\"></script>\r\n");
      out.write("	<!-- Skycons -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/skycons/skycons.js\"></script>\r\n");
      out.write("	<!-- Flot -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/Flot/jquery.flot.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/Flot/jquery.flot.pie.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/Flot/jquery.flot.time.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/Flot/jquery.flot.stack.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/Flot/jquery.flot.resize.js\"></script>\r\n");
      out.write("	<!-- Flot plugins -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/flot.orderbars/js/jquery.flot.orderBars.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/flot-spline/js/jquery.flot.spline.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/flot.curvedlines/curvedLines.js\"></script>\r\n");
      out.write("	<!-- DateJS -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/DateJS/build/date.js\"></script>\r\n");
      out.write("	<!-- JQVMap -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/jqvmap/dist/jquery.vmap.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/jqvmap/dist/maps/jquery.vmap.world.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/jqvmap/examples/js/jquery.vmap.sampledata.js\"></script>\r\n");
      out.write("	<!-- bootstrap-daterangepicker -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/moment/min/moment.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"vendors/bootstrap-daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Custom Theme Scripts -->\r\n");
      out.write("	<script src=\"build/js/custom.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
